# .github/workflows/test_actions_gcm_check.yml
name: Test GCD Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: ls -l

      - run: ./test_cal_gcm_check
        shell: bash
